[package]
name = "cure_coverage"
version = "0.1.0"
edition = "2021"

[dependencies]
byteorder = "1.4"
object = "0.34.0"
flate2 = "1.0.28"
md5 = "0.7.0"
hex = "0.4.3"
rustc-demangle = "0.1"
regex = "1"
rand = "0.8"
ff = "0.13.0"
serde_json="1.0"
serde = { version = "1.0.*", default-features = false, features = ["derive"] }
